### ISSUE TITLE
Adding a second follower 

### ISSUE THREAD

**Issue by Kennjo** [ctu-mrs/leader_follower_task#3]
I would like to add a second follower for testing some formation flying, and would appreciate some advice and pointers on which files and what configurations I should use to add a 2nd follower.

**Comment by stibipet** [comment]
Hi,
you can spawn additional drones using the [MRS Drone spawner](https://ctu-mrs.github.io/docs/simulation/drone_spawner.html). Afterwards, you will need to launch the control and the UV tracking components for the new drone.

I would recommend automating everything in a tmuxinator session. You can copy and extend the session config in `uvdar_leader_follower/tmux_scripts/simulation_two_drones/session.yml`

It should be fairly easy to understand, even without prior experience with tmuxinator. You can define new windows (these are the terminal tabs), and within the windows define new panes. It's handy to keep functionally similar programs running in one window. That's why we run the control core for all drones from the control window. If you add a third drone, just add one more pane to the window and make sure to change the UAV_NAME to a new and unique one (e.g. uav3).

The same goes for all the remaining components. If you want a second observer with cameras, you should use the same nodes as uav2. The extension could go something like this...

```
- spawn:
      layout: tiled
      panes:
        - waitForSimulation; rosservice call /mrs_drone_spawner/spawn "1 $UAV_TYPE --enable-rangefinder --enable-ground-truth --pos_file `pwd`/pos1.yaml --enable-uv-leds --uvled-fr-r 15 --uvled-fr-l 15"
        - waitForSimulation; sleep 10; rosservice call /mrs_drone_spawner/spawn "2 $UAV_TYPE --enable-rangefinder --enable-ground-truth --pos_file `pwd`/pos2.yaml --enable-uv-camera --uvcam-calib-file `rospack find uvdar_core`/include/OCamCalib/config/calib_results_bf_uv_fe.txt"
        - waitForSimulation; sleep 15; rosservice call /mrs_drone_spawner/spawn "3 $UAV_TYPE --enable-rangefinder --enable-ground-truth --enable-uv-camera --uvcam-calib-file `rospack find uvdar_core`/include/OCamCalib/config/calib_results_bf_uv_fe.txt"
  - control:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForOdometry; roslaunch mrs_uav_general core.launch config_constraint_manager:=./custom_configs/constraint_manager.yaml
        - export UAV_NAME=uav2; waitForOdometry; roslaunch mrs_uav_general core.launch config_constraint_manager:=./custom_configs/constraint_manager.yaml
        - export UAV_NAME=uav3; waitForOdometry; roslaunch mrs_uav_general core.launch config_constraint_manager:=./custom_configs/constraint_manager.yaml`
        
        ...

```

As for the actual control of more vehicles, the current architecture of this task is not really suited for more than one follower, but you can still make it work with a bit of effort. The control commands are being sent into the drone from a `summer_school_supervisor` node, specifically the `supervisor.cpp`. You will have to add more reference publishers, and connect each one into a separate vehicle. The exact topics are defined in the launch file `summer_school_supervisor/launch/supervisor.launch`. Keep in mind, that the topics are grouped under a namespace for each vehicle (e.g. uav2 has the control reference under /uav1/control_manager/reference).

Good luck
Petr
